spring:
  application:
    name: demoservice

server:
  port: 9090

springdoc:
  api-docs:
    path: /api-docs
  packagesToScan: com.tutorialspoint.demo
  swagger-ui:
    path: /swagger-ui.html

#server:
#  port: 443
#  ssl:
#    key-store: C:/TEMP/demo/SSL/keystore.p12
#    key-store-password: changeit
#    keyStoreType: PKCS12
#    keyAlias: tomcat